### PR TITLE
Fix #19 by removing getkey package; Install works on Windows

### LINKED ISSUE #19: Can't install on windows
`getkey` doesn't work on windows. There is a [workaround](https://github.com/kcsaff/getkey/issues/2#issuecomment-611278429). Should try to find a different library that is maintained.

### PR DESCRIPTION
**Pull request by pmayd**
remove getkey dependency from poetry.lock and pyproject.toml; replace… getkey and quit_display() function instead of a simple console.print(layout) from rich.console package to display the bite; update README with working instructions for windows

### CODE REVIEW

**Comment by pmayd** [comment]
Closes #19

**Comment by rhelmstedter** [comment]
To clarify my understanding, this eliminates the need for getkey by just printing the display instead of creating a Live loop? Love it.

**Comment by pmayd** [comment]
> To clarify my understanding, this eliminates the need for getkey by just printing the display instead of creating a Live loop? Love it.

Exactly

**Comment by pmayd** [comment]
I made a little mistake and forgot to delete the quit_display function in my PR so you can delete this deprecated function now, too @rhelmstedter

**Comment by rhelmstedter** [comment]
Saw that `quit_display()` was there. It's already gone 👍

**Pull request merged**
